name: Install and cache dependencies

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm install
