name: Frontend CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  install:
    uses: ./.github/workflows/install.yml
    with:
      node-version: '22.x'

  build:
    needs: install
    uses: ./.github/workflows/build.yml
    with:
      node-version: '22.x'

  lint:
    needs: install
    uses: ./.github/workflows/lint.yml
    with:
      node-version: '22.x'

  tests:
    needs: install
    uses: ./.github/workflows/tests.yml
    with:
      node-version: '22.x'

  storybook:
    needs: install
    uses: ./.github/workflows/storybook.yml
    with:
      node-version: '12.x'
